name: ecard_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
#  lottie: ^3.3.1
#  google_fonts: ^6.2.1
#  linear_progress_bar: ^1.1.3
#  flutter_advanced_switch: ^3.1.0
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.8.0
  loading_animation_widget: ^1.3.0
#  flutter_colorpicker: ^1.1.0
#  flutter_otp_text_field: ^1.4.0+2
#  permission_handler: ^11.3.1
#  # qr_code_scanner: ^1.0.1
#  qr_flutter: ^4.1.0
#  image_picker: ^1.1.2
#  flashy_tab_bar2: ^0.0.10
#  graphql_flutter: ^5.2.0-beta.8
#  sqflite: ^2.4.1
#  flutter_contacts: ^1.1.9+2
#  touchable_opacity: ^1.2.0
#  modal_bottom_sheet: ^3.0.0
#  flutter_slidable: ^3.1.2
#  connectivity_plus: ^6.1.2
#  share_plus: ^10.1.4
#  clipboard: ^0.1.3
#  url_launcher: ^6.3.1
#  skeletonizer: ^1.4.3
#  gallery_picker: ^0.5.1
#  geolocator: ^13.0.2
#  flutter_barcode_scanner: ^2.0.0
#  flutter_barcode_sdk: ^2.2.8
#  camera: ^0.11.0+2
#  qr_code_scanner_plus: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/splash-card-image-front.jpg
    - assets/images/splash-card-image-back.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf


